import type { DesktopClient } from "@desktop-foundation/bridge";
import { AuthGuard, DesktopAppShell, DesktopLoginPage, useSession, type DesktopLoginConfig } from "@desktop-foundation/app-shell";
import { DesktopLayout, LoadingBlock, PageHeader } from "@desktop-foundation/ui-react";
import { DashboardPage } from "./pages/DashboardPage";
import { productAdapter } from "./product-adapter";

const loginConfig: DesktopLoginConfig = {
  defaultPayload: { account: "operator", password: "demo", remember: true },
  login: async (_client, payload) => {
    if (!payload.account || !payload.password) throw new Error("Account and password are required");
    return { token: "local-demo-token", user: productAdapter.user, remember: payload.remember };
  }
};

function ProductWorkspace() {
  const session = useSession();
  const adapter = productAdapter;

  return (
    <DesktopLayout
      variant={adapter.layout}
      brand={adapter.brand}
      menus={adapter.menus}
      user={session.user ?? adapter.user}
      userMenuItems={adapter.userMenuItems}
      topbarRight={adapter.topbarRight}
      onLogout={session.clearSession}
    >
      <PageHeader title="Dashboard" description="A clean desktop product shell generated by desktop-foundation." />
      <DashboardPage />
    </DesktopLayout>
  );
}

export function App({ client }: { client: DesktopClient }) {
  const adapter = productAdapter;

  return (
    <DesktopAppShell
      theme={adapter.theme}
      className={adapter.className}
      client={client}
      locale={adapter.locale}
      messages={adapter.messages}
      dictionaries={adapter.dictionaries}
      accessControl={adapter.accessControl}
      session={{ loadUser: async () => adapter.user }}
    >
      <AuthGuard
        checkingFallback={<LoadingBlock rows={4} />}
        fallback={
          <DesktopLoginPage
            template={adapter.loginTemplate}
            brand={adapter.brand}
            title="Product workspace login"
            subtitle="Use the product account to enter the desktop workspace."
            login={loginConfig}
          />
        }
      >
        <ProductWorkspace />
      </AuthGuard>
    </DesktopAppShell>
  );
}
