import type { DesktopClient } from "@desktop-foundation/bridge";
import { DesktopAppShell } from "@desktop-foundation/app-shell";
import { DesktopLayout, PageHeader } from "@desktop-foundation/ui-react";
import { DashboardPage } from "./pages/DashboardPage";
import { productAdapter } from "./product-adapter";

export function App({ client }: { client: DesktopClient }) {
  const adapter = productAdapter;

  return (
    <DesktopAppShell theme={adapter.theme} className={adapter.className} client={client}>
      <DesktopLayout
        variant={adapter.layout}
        brand={adapter.brand}
        menus={adapter.menus}
        user={adapter.user}
        userMenuItems={adapter.userMenuItems}
        topbarRight={adapter.topbarRight}
      >
        <PageHeader title="Dashboard" description="A clean desktop product shell generated by desktop-foundation." />
        <DashboardPage />
      </DesktopLayout>
    </DesktopAppShell>
  );
}
