import type { DesktopClient } from "@desktop-foundation/bridge";
import { DesktopAppShell } from "@desktop-foundation/app-shell";
import { Button, DesktopLayout, PageHeader } from "@desktop-foundation/ui-react";
import { menus } from "./menus";
import { DashboardPage } from "./pages/DashboardPage";
import { productTheme } from "./theme";

export function App({ client }: { client: DesktopClient }) {
  return (
    <DesktopAppShell theme={productTheme} client={client}>
      <DesktopLayout
        brand={{ name: "{{APP_NAME}}" }}
        menus={menus}
        user={{ name: "Admin", role: "Owner" }}
        topbarRight={<Button size="sm" variant="outline">Settings</Button>}
      >
        <PageHeader title="Dashboard" description="A clean desktop product shell generated by desktop-foundation." />
        <DashboardPage />
      </DesktopLayout>
    </DesktopAppShell>
  );
}
